development:
  adapter: postgresql
  database: IVI_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: IVI_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: IVI_production
  pool: 5
  timeout: 5000

